# Generated by Django 5.0.2 on 2024-10-18 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='srmb.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('État des résultats', 'État des résultats'), ('Bilan', 'Bilan'), ('Flux de trésorerie', 'Flux de trésorerie')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='srmb.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='EtatDesResultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_des_resultats', to='srmb.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fixed_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_term_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='srmb.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='RapportDeFluxDeTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('operating_cash_inflows', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_cash_outflows', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investing_cash_inflows', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investing_cash_outflows', models.DecimalField(decimal_places=2, max_digits=15)),
                ('financing_cash_inflows', models.DecimalField(decimal_places=2, max_digits=15)),
                ('financing_cash_outflows', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, max_digits=15)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flux_de_tresorerie', to='srmb.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='srmb.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='srmb.entreprise')),
            ],
        ),
    ]
