# Generated by Django 5.0.2 on 2024-10-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='etatdesresultats',
            name='report',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='rapportdefluxdetresorerie',
            name='report',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='enterprise',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='enterprise',
            new_name='entreprise',
        ),
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('liquide', 'Liquide'), ('stocks', 'Stocks')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs', to='srmb.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[("Dépenses d'exploitation", "Dépenses d'exploitation"), ('Salaires', 'Salaires'), ('Loyer', 'Loyer'), ('Impôts et taxes', 'Impôts et taxes'), ('Dépenses financières', 'Dépenses financières'), ('autre', 'Autre')], max_length=50)),
                ('type_flux_tresorerie', models.CharField(choices=[('opérationnelle', 'Opérationnelle'), ('investissement', 'Investissement'), ('financement', 'Financement')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='srmb.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Passif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('emprunts', 'Emprunts'), ('dattes', 'Dattes'), ('fournisseur', 'Fournisseur'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passifs', to='srmb.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('categorie', models.CharField(choices=[('Vente', 'Vente'), ('Service', 'Service'), ('Autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='srmb.entreprise')),
            ],
        ),
        migrations.DeleteModel(
            name='Bilan',
        ),
        migrations.DeleteModel(
            name='Depense',
        ),
        migrations.DeleteModel(
            name='EtatDesResultats',
        ),
        migrations.DeleteModel(
            name='Rapport',
        ),
        migrations.DeleteModel(
            name='RapportDeFluxDeTresorerie',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
