# Generated by Django 5.1.2 on 2024-10-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmb', '0003_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
