# Generated by Django 5.1.2 on 2024-10-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmb', '0004_alter_entreprise_email_delete_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
