# Generated by Django 5.1.2 on 2024-10-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srmb', '0004_revenue_type_flux_tresorerie'),
        ('srmb', '0005_utilisateur_last_login_alter_utilisateur_password'),
    ]

    operations = [
    ]
